
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LAB-RPL1-PC06
 */
public class NewJFrame extends javax.swing.JFrame {
    Connection koneksi;
    String id = "";
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        koneksi();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        agama = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        laki = new javax.swing.JRadioButton();
        pr = new javax.swing.JRadioButton();
        asal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PENDAFTARAN SISWA BARU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAMA                  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 59, -1, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 56, 249, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ALAMAT              :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 96, -1, -1));

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane1.setViewportView(alamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 96, 250, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("AGAMA                  :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 249, -1, -1));

        agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "islam", "kristen", "katolik", "budha", "hindu" }));
        getContentPane().add(agama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 246, 253, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SEKOLAH ASAL     :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Alamat", "Jenis Kelamin", "Agama", "Asal"
            }
        ));
        jScrollPane2.setViewportView(tabel);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 316, 552, 100));

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 83, 77, -1));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 115, 77, -1));

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 147, 77, -1));

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 179, 77, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("JENIS KELAMIN     :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 200, 110, 30));

        buttonGroup1.add(laki);
        laki.setText("laki-laki");
        getContentPane().add(laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        buttonGroup1.add(pr);
        pr.setText("perempuan");
        getContentPane().add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));
        getContentPane().add(asal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 250, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        if(id == ""){
        create();
        }else{
        update();
        }
        
    }//GEN-LAST:event_simpanActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        delete();
    }//GEN-LAST:event_hapusActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        edit();
    }//GEN-LAST:event_editActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clear();
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> agama;
    private javax.swing.JTextArea alamat;
    private javax.swing.JTextField asal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton pr;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
    private void koneksi(){
        try {
            String server = "jdbc:mysql://localhost:3306/rpl1_wahyuu";
        String user = "root";
        String pass = "";
        
        DriverManager.registerDriver(new com.mysql.cj.jdbc.Driver());
        koneksi = DriverManager.getConnection(server, user, pass);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }

    private void tampil(){
    DefaultTableModel data = (DefaultTableModel) tabel.getModel();
    data.setRowCount(0);
        try {
            String sql = "SELECT * FROM tb_daftar";
            ResultSet res = koneksi.createStatement().executeQuery(sql);
            
            while (res.next()) {
                data.addRow(new Object[]{
                    res.getString(1), res.getString(2), res.getString(3),
                    res.getString(4), res.getString(5), res.getString(6)
                });
                
            }
            tabel.setModel(data);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
       private void create(){
           try {
            String jk = (laki.isSelected()) ? "laki-laki" : "perempuan";
            String sql = "INSERT INTO tb_daftar VALUES(null,"
                    +"'" + nama.getText() +"'," 
                    +"'" + alamat.getText() +"',"
                    +"'" + jk +"',"
                    +"'" + agama.getSelectedItem().toString() +"',"
                    +"'" + asal.getText() +"')";
           
               int res = koneksi.createStatement().executeUpdate(sql);
               
               if(res > -1){
               tampil();
               nama.setText("");
               alamat.setText("");
               laki.setSelected(false);
               pr.setSelected(false);
               agama.setSelectedIndex(0);
               asal.setText("");
               }
           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, e);
           }
       }
       
       private void delete(){
       int row = tabel.getSelectedRow();
       String id = tabel.getValueAt(row, 0).toString();
       
           try {
               String sql = "DELETE FROM tb_daftar WHERE id="+id;
               int res = koneksi.createStatement().executeUpdate(sql);
               
               if(res > -1){
               tampil();
               }
           } catch (Exception e) {
           }
       }
       
       private void edit(){
       int row = tabel.getSelectedRow();
       String id_siswa = tabel.getModel().getValueAt(row, 0).toString();
       
           try {
               String sql = "SELECT * FROM tb_daftar WHERE id="+id_siswa;
               ResultSet res = koneksi.createStatement().executeQuery(sql);
               
               while(res.next()){
               id = res.getString(1);
               nama.setText(res.getString(2));
               alamat.setText(res.getString(3));
               if(res.getString(4).equals("laki-laki")){
               laki.setSelected(true);
               }else{
               pr.setSelected(true);
               }
               agama.setSelectedItem(res.getString(5));
               asal.setText(res.getString(6));
               edit.setEnabled(false);
               }
           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, e);
           }
       }
       
       private void clear (){
               id = null;
               nama.setText("");
               alamat.setText("");
               laki.setSelected(false);
               pr.setSelected(false);
               agama.setSelectedIndex(0);
               asal.setText("");
               edit.setEnabled(true);
       }
       
       private void update(){
           
            String jk = (laki.isSelected()) ? "laki-laki" : "perempuan";
            String sql = "UPDATE tb_daftar SET "
                    +"nama = '" + nama.getText() +"'," 
                    +"alamat = '" + alamat.getText() +"',"
                    +"jenis_kelamin = '" + jk +"',"
                    +"agama = '" + agama.getSelectedItem().toString() +"',"
                    +"sekolah_asal = '" + asal.getText() +"' "
                    + "WHERE id = "+id;
           try {
               int res = koneksi.createStatement().executeUpdate(sql);
               
               if(res > -1){
               tampil();
               clear();
               }
           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, e);
           }
       }
}
